keys:
  users:
    - &profidev_home age1g0eg4sdf7tzndhs9at7gy9rrdrllsmktlq6g7yy6gjf6rg4sy3kqjmrgcu
    - &profidev_laptop age133tjrtvw3mcyq4l44xsxpwh4gkhs9f4eurun4rah7rygns50qf0qs06yps
  hosts:
    - &home age1n5e38zqazrzdaahaj6lvxuvve2lqq6hv08smfpew75m6ycarh9gqrfn3ur
    - &laptop age1e3wtf94uusd6g20c6pmgwz2he8hnr252yfa2nmz3epwuwx62v5jsma63zh
    - &node2 "age18vrxup6senmw4vf7v7xlrwqw8ej8wc7vudv68jusfmxrsw3tqvzql6w0py"
    - &node2 age18vrxup6senmw4vf7v7xlrwqw8ej8wc7vudv68jusfmxrsw3tqvzql6w0py
    - &node1 age1yhm65sct48w0kucgem8c3qn7ps6vt8ezhlnkvqj26jmyvvghh93qheu0c6
    - &node3 age166mw9ala5vht0sz94wn44m08jqqddr76y7ktqdulma04j8ht03ksv6v4vz
creation_rules:
  - path_regex: sops\.yaml$
    key_groups:
      - age:
          - *profidev_home
          - *profidev_laptop
          - *home
          - *laptop
          - *node2
          - *node1
          - *node3
