keys:
  users:
    - &profidev_home age1g0eg4sdf7tzndhs9at7gy9rrdrllsmktlq6g7yy6gjf6rg4sy3kqjmrgcu
    - &profidev_laptop age133tjrtvw3mcyq4l44xsxpwh4gkhs9f4eurun4rah7rygns50qf0qs06yps
  hosts:
    - &home age1n5e38zqazrzdaahaj6lvxuvve2lqq6hv08smfpew75m6ycarh9gqrfn3ur
    - &laptop age1e3wtf94uusd6g20c6pmgwz2he8hnr252yfa2nmz3epwuwx62v5jsma63zh
    - &node2 "age1350lye05p5v3u2wv4xjexphss52tw855a3kzyq6258t08kakg9vqzxxxvp"
    - &node2 age1350lye05p5v3u2wv4xjexphss52tw855a3kzyq6258t08kakg9vqzxxxvp
    - &node1 age10efpdlkrgt3z7w5phz0lfumpqklvt78hhsr0kx3q0694xpnd0utsjucckg
creation_rules:
  - path_regex: sops\.yaml$
    key_groups:
      - age:
          - *profidev_home
          - *profidev_laptop
          - *home
          - *laptop
          - *node2
          - *node1
