---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: positron-backend
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: ClusterSecretStore
  target:
    name: positron-backend
  dataFrom:
    - extract:
        key: {{ .Values.secret.path }}
