{
 "title": "Coder Workspaces",
 "tags": [ "coder" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "workspace_name",
    "label": "Workspace Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,workspace_name)"
    }
   },
   {
    "name": "template_name",
    "label": "Template Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,template_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1.2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=`coder`}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{namespace=`coder`})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  round(increase(kube_pod_container_status_restarts_total{namespace=`coder`}[$__interval]))\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{namespace=`coder`}[$__interval])\n)",
     "legendFormat": "{{pod}}:{{reason}}"
    }
   ]
  },
  { "title": "Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18.2 } },
  {
   "title": "Successful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 27.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_name, workspace_owner, status, template_name, template_version, workspace_transition) (\n  # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n  # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n  ((\n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n  ) >= 0) \n  or coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace by User/Template",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner, template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{workspace_owner}}:{{template_name}}"
    }
   ]
  },
  {
   "title": "Template Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Template Version Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name, template_version) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{template_name}}:{{template_version}}"
    }
   ]
  }
 ]
}