---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proton-backend
  namespace: proton
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: proton-backend
  dataFrom:
    - extract:
        key: apps/proton
