secret:
  storeName: cluster-secret-store
  path: apps/proton

backend:
  replicaCount: 1
  extraVolumeMounts:
    - mountPath: /etc/ssl/certs/e11529a0.0
      subPath: e11529a0.0
      name: cluster-ca-cert
      readOnly: true
  extraVolumes:
    - name: cluster-ca-cert
      secret:
        defaultMode: 420
        secretName: cluster-ca-cert

  podLabels: {}

  ingress:
    className: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: proton/cloudflare-ca-cert
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    host: proton.profidev.io
    tls:
      - hosts:
          - profidev.io
          - "*.profi.dev"
        secretName: cloudflare-cert
