apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
              - pgrep
              - {{ .Chart.Name }}
            initialDelaySeconds: 10
            periodSeconds: 60
        env:
        {{- range $key, $value := .Values.secrets }}
          - name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                name: {{  $value.name }}
                key: {{  $value.key }}
        {{- end }}
          - name: VAULT_URL
            value: "{{ .Values.vault_url }}"
