apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers: {{ $default_tag := replace " " "" (cat "vault-auto-unseal-" .Chart.Version) }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ default $default_tag .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
              - pgrep
              - app
            initialDelaySeconds: 10
            periodSeconds: 60
        env:
        {{- range $key, $value := .Values.secrets }}
          - name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                name: {{  $value.name }}
                key: {{  $value.key }}
        {{- end }}
          - name: VAULT_URL
            value: "{{ .Values.vault_url }}"
