secret:
  storeName: cluster-secret-store
  path: apps/auto-clean-bot

bot:
  replicaCount: 1
  extraVolumes:
    - name: cluster-ca-cert
      secret:
        defaultMode: 420
        secretName: cluster-ca-cert
  extraVolumeMounts:
    - mountPath: /etc/ssl/certs/e11529a0.0
      subPath: e11529a0.0
      name: cluster-ca-cert
      readOnly: true

  podLabels:
    postgres-access: "true"
