---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-bot
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.bot.replicaCount | default 1 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-bot
        {{- with .Values.bot.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - tty: true
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-bot
          image: ghcr.io/profiidev/{{ .Chart.Name }}/bot:{{ .Chart.Version }}
          imagePullPolicy: Always
          name: {{ .Chart.Name }}-bot
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- with .Values.bot.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- with .Values.bot.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
