---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  selector: app == '{{ .Chart.Name }}-bot'
  types:
    - Ingress
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        notNets:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
        ports:
          - 443
