{
 "title": "PgBouncer cluster overview",
 "tags": [ "pgbouncer" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(pgbouncer_databases_current_connections{job=\"pgbouncer-exporter-prometheus-pgbouncer-exporter\"}, job)"
   },
   {
    "name": "pgbouncer_cluster",
    "label": "Pgbouncer_cluster",
    "query": "label_values(pgbouncer_databases_current_connections{job=~\"$job\"}, pgbouncer_cluster)"
   },
   {
    "name": "top_database_count",
    "label": "Top database count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Top databases by active connections",
   "type": "timeseries",
   "description": "Top databases by current number of active client connections.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "topk by(database, instance, pgbouncer_cluster)($top_database_count, pgbouncer_pools_client_active_connections{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"})",
     "legendFormat": "{{pgbouncer_cluster}} - {{instance}} - {{database}}"
    }
   ]
  },
  { "title": "PgBouncer alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Top databases by queries processed",
   "type": "timeseries",
   "description": "Top databases by rate of SQL queries pooled by PgBouncer.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk by(database, instance, pgbouncer_cluster)($top_database_count, rate(pgbouncer_stats_queries_pooled_total{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{pgbouncer_cluster}} - {{instance}} - {{database}}"
    }
   ]
  },
  {
   "title": "Top databases by average query duration",
   "type": "timeseries",
   "description": "Top databases by average duration of queries being processed by PgBouncer.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk by(database, instance, pgbouncer_cluster)($top_database_count, 1000 * increase(pgbouncer_stats_queries_duration_seconds_total{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"}[$__interval:]) / clamp_min(increase(pgbouncer_stats_queries_pooled_total{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"}[$__interval:]), 1))",
     "legendFormat": "{{pgbouncer_cluster}} - {{instance}} - {{database}}"
    }
   ]
  },
  {
   "title": "Top databases by network traffic",
   "type": "timeseries",
   "description": "Top databases by volume of network traffic.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk by(database, instance, pgbouncer_cluster)($top_database_count, rate(pgbouncer_stats_received_bytes_total{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{pgbouncer_cluster}} - {{instance}} - {{database}} - received"
    },
    {
     "expr": "topk by(database, instance, pgbouncer_cluster)($top_database_count, rate(pgbouncer_stats_sent_bytes_total{job=~\"$job\",pgbouncer_cluster=~\"$pgbouncer_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{pgbouncer_cluster}} - {{instance}} - {{database}} - sent"
    }
   ]
  }
 ]
}