{
 "title": "PgBouncer overview",
 "tags": [ "pgbouncer" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(pgbouncer_databases_current_connections{job=\"pgbouncer-exporter-prometheus-pgbouncer-exporter\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pgbouncer_databases_current_connections{job=~\"$job\"}, instance)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pgbouncer_databases_current_connections{job=\"pgbouncer-exporter-prometheus-pgbouncer-exporter\"}, database)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Client waiting connections",
   "type": "stat",
   "description": "Current number of client connections waiting on a server connection.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_waiting_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Active client connections",
   "type": "stat",
   "description": "Current number of active client connections.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_active_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Active server connections",
   "type": "stat",
   "description": "Current number of client connections that are linked to a server connection and able to process queries.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Max database connections",
   "type": "stat",
   "description": "Maximum number of allowed connections for database.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_databases_max_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Max user connections",
   "type": "stat",
   "description": "Maximum number of server connections per user allowed.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_config_max_user_connections{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max client connections",
   "type": "stat",
   "description": "Maximum number of client connections allowed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_config_max_client_connections{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 4 } },
  {
   "title": "Queries processed",
   "type": "timeseries",
   "description": "Rate of SQL queries pooled by PgBouncer.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stats_queries_pooled_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Queries average duration / $__interval",
   "type": "timeseries",
   "description": "Average duration of queries being processed by PgBouncer.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * increase(pgbouncer_stats_queries_duration_seconds_total{job=~\"$job\"base\"}[$__interval:]) / clamp_min(increase(pgbouncer_stats_queries_pooled_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__interval:]), 1)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 11 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Volume in bytes of network traffic received by PgBouncer.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stats_received_bytes_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__rate_interval])",
     "legendFormat": "{{database}} - received"
    },
    {
     "expr": "rate(pgbouncer_stats_sent_bytes_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__rate_interval])",
     "legendFormat": "{{database}} - sent"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 18 } },
  {
   "title": "SQL transaction rate",
   "type": "timeseries",
   "description": "Rate of SQL transactions pooled.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stats_sql_transactions_pooled_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "SQL average transaction duration / $__interval",
   "type": "timeseries",
   "description": "Average duration of SQL transactions pooled.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * increase(pgbouncer_stats_server_in_transaction_seconds_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__interval:]) / clamp_min(increase(pgbouncer_stats_sql_transactions_pooled_total{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}[$__interval:]), 1)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 25 } },
  {
   "title": "Server connections",
   "type": "timeseries",
   "description": "Number of various server connection states.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_server_idle_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}} - idle"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}} - used"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}} - login"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}} - testing"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 32 } },
  {
   "title": "Active client connections",
   "type": "timeseries",
   "description": "Current number of active client connections.\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Waiting clients",
   "type": "timeseries",
   "description": "Current number of client connections waiting on a server connection.\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "clients" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_waiting_connections{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Max client wait time",
   "type": "timeseries",
   "description": "Age of the oldest unserved client connection in seconds.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_maxwait_seconds{job=~\"$job\",instance=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}