secret:
  storeName: cluster-secret-store
  path: apps/charm

backend:
  replicaCount: 1
  imagePullSecret: ghcr-profidev
  extraVolumes:
    - name: cluster-ca-cert
      secret:
        defaultMode: 420
        secretName: cluster-ca-cert
  extraVolumeMounts:
    - mountPath: /etc/ssl/certs/e11529a0.0
      subPath: e11529a0.0
      name: cluster-ca-cert
      readOnly: true

  ingress:
    className: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: charm/cloudflare-ca-cert
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    host: charm.profidev.io
    tls:
      - hosts:
          - profidev.io
          - "*.profi.dev"
        secretName: cloudflare-cert

frontend:
  replicaCount: 1
  imagePullSecret: ghcr-profidev

  ingress:
    className: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: charm/cloudflare-ca-cert
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    host: charm.profidev.io
    tls:
      - hosts:
          - profidev.io
          - "*.profi.dev"
        secretName: cloudflare-cert
