global:
  enabled: true
  tlsDisable: false

injector:
  enabled: true
  replicas: 1

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca

  extraVolumes:
    - type: secret
      name: vault-server-tls

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: longhorn

  auditStorage:
    size: 10Gi
    storageClass: longhorn

  standalone:
    enabled: true
    config: |
      ui = true
      cluster_name = "vault-integrated-storage"
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
      }
      storage "file" {
        path = "/vault/data"
      }

ui:
  enabled: true
