apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-backend-ingress
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  selector: app == '{{ .Chart.Name }}-backend'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: kubernetes.io/metadata.name == 'kube-system'
        selector: app.kubernetes.io/name == 'rke2-ingress-nginx'
      destination:
        ports:
          - 8000
