---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Chart.Name }}-backend
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backend.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/backend/(.*)"
            backend:
              service:
                name: {{ .Chart.Name }}-backend
                port:
                  number: 8000
          - pathType: ImplementationSpecific
            path: "/.well-known/(.*)"
            backend:
              service:
                name: {{ .Chart.Name }}-backend
                port:
                  number: 8000
  {{- with .Values.backend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
