---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount | default 1 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.backend.imagePullSecret | default "ghcr-profidev" }}
      containers:
        - tty: true
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-backend
          image: ghcr.io/profiidev/{{ .Chart.Name }}/{{ .Chart.Name }}-backend:{{ .Chart.Version }}
          imagePullPolicy: Always
          name: {{ .Chart.Name }}-backend
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- with .Values.backend.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- with .Values.backend.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
