---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ .Chart.Name }}-frontend
  type: ClusterIP
