name: Bump Helm Chart Version

on:
  repository_dispatch:
    types: [bump-chart]

jobs:
  bump-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
        uses: actions/checkout@v5

      - name: Bump chart version
        id: bump_chart
        run: |
          chart_name=${{ github.event.client_payload.chart_name }}
          chart_version=${{ github.event.client_payload.chart_version }}
          echo "Bumping version for $chart_name to $chart_version"
          sed -i "s/^version: .*/version: $chart_version/" charts/$chart_name/Chart.yaml
        
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Bump chart version for ${{ github.event.client_payload.chart_name }} to ${{ github.event.client_payload.chart_version }}"
          branch: chore/bump-chart-version-${{ github.event.client_payload.chart_name }}-${{ github.event.client_payload.chart_version }}
          title: "Bump chart version for ${{ github.event.client_payload.chart_name }} to ${{ github.event.client_payload.chart_version }}"
          body: "This PR bumps the chart version for ${{ github.event.client_payload.chart_name }} to ${{ github.event.client_payload.chart_version }}."
          base: main
          sign-commits: true
          labels: bump-chart
