name: Helm Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Helm Charts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser job
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
