[package]
name = "vault-auto-unseal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
signal-hook = "0.3.17"
ureq = { version = "3.0.10", features = ["json"] }
